### Used when starting quarkus app in development mode, e.g. mvn quarkus:dev

app.id=command-router
short.name=cmd-router

hono.commandRouter.amqp.insecurePortEnabled=true
hono.commandRouter.amqp.insecurePortBindAddress=0.0.0.0
hono.commandRouter.amqp.insecurePort=${fixed.commandrouter.amqp.port}

hono.commandRouter.cache.redis.hosts=redis://${docker.host.address:localhost}:${redis.port:6379}

quarkus.http.port=${fixed.commandrouter.quarkus.http.port:3088}

${quarkus.application-dev.properties}
hono.kafka.commandInternal.producerConfig."max.block.ms"=${kafka-client.producer.max-block-ms}
hono.kafka.commandInternal.producerConfig."request.timeout.ms"=${kafka-client.producer.request-timeout-ms}
hono.kafka.commandResponse.producerConfig."max.block.ms"=${kafka-client.producer.max-block-ms}
hono.kafka.commandResponse.producerConfig."request.timeout.ms"=${kafka-client.producer.request-timeout-ms}
hono.kafka.event.producerConfig."max.block.ms"=${kafka-client.producer.max-block-ms}
hono.kafka.event.producerConfig."request.timeout.ms"=${kafka-client.producer.request-timeout-ms}
hono.kafka.notification.producerConfig."max.block.ms"=${kafka-client.producer.max-block-ms}
hono.kafka.notification.producerConfig."request.timeout.ms"=${kafka-client.producer.request-timeout-ms}
